services:
  server:
    build:
      context: ./src
      dockerfile: ServerCpp/Dockerfile
    entrypoint: ["./ServerCpp"]
    command: ["3782"]
    ports:
      - "3782:3782"
    volumes:
      - ./data:/usr/src/data
    environment:
      - EX1_DIR=/usr/src/data
    networks:
      - local

  server_node:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - local

  client_python:
    build:
      context: ./src/ClientPython
      dockerfile: Dockerfile
    entrypoint: ["python3", "TCP_Client.py"]
    command: ["server", "3782"]
    depends_on:
      - server
    networks:
      - local
    stdin_open: true
    tty: true

  client_cpp:
    build:
      context: ./src/ClientCpp
      dockerfile: Dockerfile
    entrypoint: ["./tcp_c"]
    command: ["server", "3782"]
    depends_on:
      - server
    networks:
      - local
    stdin_open: true
    tty: true

networks:
  local:
    driver: bridge
