services:
  server:
    build:
      context: ./src
      dockerfile: ServerCpp/Dockerfile.Server
    entrypoint: ["./ServerCpp"]
    command: ["3782"]
    ports:
      - "3782:3782"
    volumes:
      - ./data:/usr/src/data    
    environment:
      - EX1_DIR=/usr/src/data    
    networks:
      - local

  client_python:
    build:
      context: ./src/ClientPython
      dockerfile: Dockerfile.clientPY
    entrypoint: ["python3","TCP_Client.py"]
    command: ["server","3782"]
    depends_on:
      - server
    networks:
      - local

  client_cpp:
    build:
      context: ./src/ClientCpp
      dockerfile: Dockerfile.clientCPP
    entrypoint: ["./tcp_c"]
    command: ["server", "3782"]
    depends_on:
      - server
    networks:
      - local

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16"