
FROM gcc:latest


RUN apt-get update && \
    apt-get install -y make && \
    apt-get clean


WORKDIR /usr/src/app


COPY ServerCpp/RealServer.cpp .

# Copy all other .cpp 
COPY *.cpp .

# Copy all header files
COPY *.h .


RUN g++ -std=c++17 -pthread -o ServerCpp *.cpp

# Expose server port
EXPOSE 3782


ENTRYPOINT ["./ServerCpp"]
